#!/usr/bin/env bash
set -euo pipefail
cd /workspace/writeable/code/camera_motion_disentangle

PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python /workspace/writeable/environments/kubric_official/bin/python /workspace/writeable/code/camera_motion_disentangle/scripts/generate_official_kubric_review_bank.py --run-id kubric_batch_v1_shard_0000 --run-root /workspace/writeable/datasets/camera_motion_disentangle/kubric_batch_v1 --camera-limit 5 --physics-limit 6 --pairs 40 --frames 96 --width 640 --height 480 --seed 20260706 --overwrite --no-render
PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python /workspace/writeable/environments/kubric_official/bin/python /workspace/writeable/code/camera_motion_disentangle/scripts/generate_official_kubric_review_bank.py --run-id kubric_batch_v1_shard_0001 --run-root /workspace/writeable/datasets/camera_motion_disentangle/kubric_batch_v1 --camera-limit 5 --physics-limit 6 --pairs 40 --frames 132 --width 640 --height 480 --seed 20260707 --overwrite --no-render
PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python /workspace/writeable/environments/kubric_official/bin/python /workspace/writeable/code/camera_motion_disentangle/scripts/generate_official_kubric_review_bank.py --run-id kubric_batch_v1_shard_0002 --run-root /workspace/writeable/datasets/camera_motion_disentangle/kubric_batch_v1 --camera-limit 5 --physics-limit 6 --pairs 40 --frames 120 --width 640 --height 480 --seed 20260708 --overwrite --no-render
PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python /workspace/writeable/environments/kubric_official/bin/python /workspace/writeable/code/camera_motion_disentangle/scripts/generate_official_kubric_review_bank.py --run-id kubric_batch_v1_shard_0003 --run-root /workspace/writeable/datasets/camera_motion_disentangle/kubric_batch_v1 --camera-limit 5 --physics-limit 6 --pairs 40 --frames 108 --width 640 --height 480 --seed 20260709 --overwrite --no-render
PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python /workspace/writeable/environments/kubric_official/bin/python /workspace/writeable/code/camera_motion_disentangle/scripts/generate_official_kubric_review_bank.py --run-id kubric_batch_v1_shard_0004 --run-root /workspace/writeable/datasets/camera_motion_disentangle/kubric_batch_v1 --camera-limit 5 --physics-limit 6 --pairs 40 --frames 96 --width 640 --height 480 --seed 20260710 --overwrite --no-render
PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python /workspace/writeable/environments/kubric_official/bin/python /workspace/writeable/code/camera_motion_disentangle/scripts/generate_official_kubric_review_bank.py --run-id kubric_batch_v1_shard_0005 --run-root /workspace/writeable/datasets/camera_motion_disentangle/kubric_batch_v1 --camera-limit 5 --physics-limit 6 --pairs 40 --frames 108 --width 640 --height 480 --seed 20260711 --overwrite --no-render
PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python /workspace/writeable/environments/kubric_official/bin/python /workspace/writeable/code/camera_motion_disentangle/scripts/generate_official_kubric_review_bank.py --run-id kubric_batch_v1_shard_0006 --run-root /workspace/writeable/datasets/camera_motion_disentangle/kubric_batch_v1 --camera-limit 5 --physics-limit 6 --pairs 40 --frames 96 --width 640 --height 480 --seed 20260712 --overwrite --no-render
PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python /workspace/writeable/environments/kubric_official/bin/python /workspace/writeable/code/camera_motion_disentangle/scripts/generate_official_kubric_review_bank.py --run-id kubric_batch_v1_shard_0007 --run-root /workspace/writeable/datasets/camera_motion_disentangle/kubric_batch_v1 --camera-limit 5 --physics-limit 6 --pairs 40 --frames 96 --width 640 --height 480 --seed 20260713 --overwrite --no-render
PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python /workspace/writeable/environments/kubric_official/bin/python /workspace/writeable/code/camera_motion_disentangle/scripts/generate_official_kubric_review_bank.py --run-id kubric_batch_v1_shard_0008 --run-root /workspace/writeable/datasets/camera_motion_disentangle/kubric_batch_v1 --camera-limit 5 --physics-limit 6 --pairs 40 --frames 120 --width 640 --height 480 --seed 20260714 --overwrite --no-render
PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python /workspace/writeable/environments/kubric_official/bin/python /workspace/writeable/code/camera_motion_disentangle/scripts/generate_official_kubric_review_bank.py --run-id kubric_batch_v1_shard_0009 --run-root /workspace/writeable/datasets/camera_motion_disentangle/kubric_batch_v1 --camera-limit 5 --physics-limit 6 --pairs 40 --frames 84 --width 640 --height 480 --seed 20260715 --overwrite --no-render
PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python /workspace/writeable/environments/kubric_official/bin/python /workspace/writeable/code/camera_motion_disentangle/scripts/generate_official_kubric_review_bank.py --run-id kubric_batch_v1_shard_0010 --run-root /workspace/writeable/datasets/camera_motion_disentangle/kubric_batch_v1 --camera-limit 5 --physics-limit 6 --pairs 40 --frames 84 --width 640 --height 480 --seed 20260716 --overwrite --no-render
PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python /workspace/writeable/environments/kubric_official/bin/python /workspace/writeable/code/camera_motion_disentangle/scripts/generate_official_kubric_review_bank.py --run-id kubric_batch_v1_shard_0011 --run-root /workspace/writeable/datasets/camera_motion_disentangle/kubric_batch_v1 --camera-limit 5 --physics-limit 6 --pairs 40 --frames 120 --width 640 --height 480 --seed 20260717 --overwrite --no-render
PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python /workspace/writeable/environments/kubric_official/bin/python /workspace/writeable/code/camera_motion_disentangle/scripts/generate_official_kubric_review_bank.py --run-id kubric_batch_v1_shard_0012 --run-root /workspace/writeable/datasets/camera_motion_disentangle/kubric_batch_v1 --camera-limit 5 --physics-limit 6 --pairs 40 --frames 108 --width 640 --height 480 --seed 20260718 --overwrite --no-render
PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python /workspace/writeable/environments/kubric_official/bin/python /workspace/writeable/code/camera_motion_disentangle/scripts/generate_official_kubric_review_bank.py --run-id kubric_batch_v1_shard_0013 --run-root /workspace/writeable/datasets/camera_motion_disentangle/kubric_batch_v1 --camera-limit 5 --physics-limit 6 --pairs 40 --frames 96 --width 640 --height 480 --seed 20260719 --overwrite --no-render
PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python /workspace/writeable/environments/kubric_official/bin/python /workspace/writeable/code/camera_motion_disentangle/scripts/generate_official_kubric_review_bank.py --run-id kubric_batch_v1_shard_0014 --run-root /workspace/writeable/datasets/camera_motion_disentangle/kubric_batch_v1 --camera-limit 5 --physics-limit 6 --pairs 40 --frames 120 --width 640 --height 480 --seed 20260720 --overwrite --no-render
PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python /workspace/writeable/environments/kubric_official/bin/python /workspace/writeable/code/camera_motion_disentangle/scripts/generate_official_kubric_review_bank.py --run-id kubric_batch_v1_shard_0015 --run-root /workspace/writeable/datasets/camera_motion_disentangle/kubric_batch_v1 --camera-limit 5 --physics-limit 6 --pairs 40 --frames 84 --width 640 --height 480 --seed 20260721 --overwrite --no-render
